server:
  port: 9527

spring:
  application:
    name: cloud-getway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
         # uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
           # - Between=2020-12-27T10:59:34.102+08:00[Asia/Shanghai],2020-12-30T10:59:34.102+08:00[Asia/Shanghai]
            - Cookie=username,yinkai


        - id: payment_routh2
         # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: cloud-gateway-service
